version: "3.8"

services:

  db: # This is the DEFAULT `Server` name in `adminer`. DO NOT CHANGE THIS NAME.
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      # - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql # CONST Directory names for InnoDB. DO NOT CHANGE THIS NAME.
      - "./initdb.sql:/docker-entrypoint-initdb.d/1.sql"

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - $ADMINER_LOCAL_PORT:$ADMINER_DOCKER_PORT

  app:
    depends_on:
      - db
    build: .
    restart: always
    environment:
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=123456
      - MYSQLDB_DATABASE=cinemadb
      - MYSQLDB_HOST=db
      - MYSQLDB_PORT=$MYSQLDB_DOCKER_PORT
      - NODE_PORT=$NODE_LOCAL_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
      - $NODE_DEBUGGER_PORT:$NODE_DEBUGGER_PORT
    stdin_open: true
    tty: true


volumes:
  db_data: {}


#------------------------------------
# If you want to rename this network:

#networks:
#  default:
#    name: YOUR-NETWORK-NAME