version: "3.8"

services:

  db: # This is the DEFAULT `Server` name in `adminer`. DO NOT CHANGE THIS NAME.
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql # CONST Directory names for InnoDB. DO NOT CHANGE THIS NAME.

  adminer:
    image: adminer
    depends_on:
      - db # Must -> Same as the `db` service name, as declared above.
    restart: always
    env_file: ./.env
    ports:
      - $ADMINER_LOCAL_PORT:$ADMINER_DOCKER_PORT

  app:
    depends_on:
      - db # Must -> Same as the `db` service name, as declared above.
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    stdin_open: true
    tty: true


volumes:
  db_data: {}


#------------------------------------
# If you want to rename this network:

#networks:
#  default:
#    name: YOUR-NETWORK-NAME